---
version: '3.7'

services:

  node: &nodebase
    build:
      context: .
    volumes:
      - ".:/app"
      - /app/node_modules
      - "$HOME/.aws:/root/.aws"
    ports:
      - "9200:9200"

  sh:
    <<: *nodebase
    entrypoint:
      - "sh"
